### ISSUE TITLE
java 1.7

### ISSUE THREAD

**Issue by raafaar** [lordlothar99/strategy-spring-security-acl#27]
Hello,
I would really like to use strategy-spring-security-acl, but one of the requirements for my system is that it has to run on java 1.7.

So, since strategy-spring-security-acl is for java 1.8, I wonder if Is there a way for me to do this.
Or is there an old version which can be run in java 1.7?

Specifically, I am interested in the Grant functionality and maybe in the jpa functionality (if I can integrate it with ebean).

thank you in advance

**Comment by lordlothar99** [comment]
hi @raafaar ! actually the only option I think is to create a dedicated branch with 1.7 compliant code.. it doesn't seem hard to migrate code toward jdk7, I'll have a look

**Comment by lordlothar99** [comment]
this seems to work... I'm creating release 1.3.0 so it will be easier for you to integrate in your project.
You'll have to use classifier "jdk7" for all strategy-acl-security artifacts

**Comment by raafaar** [comment]
Wow! That was so fast. Thank you, I'll work with it.
