### ISSUE TITLE
Difficulty pulling artifacts from this repo as explained in the documentation

### ISSUE THREAD

**Issue by bsakweson** [lordlothar99/strategy-spring-security-acl#29]
I am working on an app that could use this library and thanks for taking some time to work on this. However, when I tried using  this as explained in your documentation, I ran into an issue. Your dependency version says "LATEST", I guess the assumption is that one would have to replace that with the latest version. I could see that you are currently working on 1.4.0-SNAPSHOT, is there a list of stable dependencies that one can use on a project. Here is the error I am getting, am I missing something? 

"The following artifacts could not be resolved:
``` com.github.lothar.security.acl:strategy-spring-security-acl-grant:jar:1.4.0-SNAPSHOT, com.github.lothar.security.acl:strategy-spring-security-acl-jpa:jar:1.4.0-SNAPSHOT: Could not find artifact com.github.lothar.security.acl:strategy-spring-security-acl-grant:jar:1.4.0-SNAPSHOT in strategy-spring-security-acl-github-repo (https://raw.github.com/lordlothar99/strategy-spring-security-acl/mvn-repo/)"```

I have the repository defined in my parent pom:

```<repositories>
	<repository>
		<id>strategy-spring-security-acl-github-repo</id>
		<url>https://raw.github.com/lordlothar99/strategy-spring-security-acl/mvn-repo/</url>
		<snapshots>
			<enabled>true</enabled>
			<updatePolicy>always</updatePolicy>
		</snapshots>
	</repository>
</repositories>

<dependency>
	<groupId>com.github.lothar.security.acl</groupId>
	<artifactId>strategy-spring-security-acl-elasticsearch</artifactId>
	<version>${acl.version}</version>
</dependency>

<dependency>
       <groupId>com.github.lothar.security.acl</groupId>
	<artifactId>strategy-spring-security-acl-grant</artifactId>
	<version>${acl.version}</version>
</dependency>

<dependency>
	<groupId>com.github.lothar.security.acl</groupId>
	<artifactId>strategy-spring-security-acl-jpa</artifactId>
	<version>${acl.version}</version>
</dependency>

<acl.version>1.4.0-SNAPSHOT</acl.version>```

My project is actually a multi-module maven project using spring-boot.

Additionally, can this work in tandem with ```EnversRevisionRepositoryFactoryBean``` hibernate envers.

Please let me know if I am missing something?

Thanks

**Comment by lordlothar99** [comment]
hi @bsakweson ; yes, documentation may be a little confusing ... snapshots versions are built by CI, but not available as maven dependencies in Github. You should use 1.3.0 instead, which is latest version avaible.
You can browse versions of the project in the `code` tab by clicking on "Branch" dropdown list, and then selecting "Tags", as every released versions have a matching tag.
Please tell me if this version doesn't work

**Comment by bsakweson** [comment]
I tried that too but it still does not work. For now I went the brut force way by manually building the code and install those artifacts in my repo so that I can play with this and see how it works. Please see the error message I am getting ```The following artifacts could not be resolved: com.github.lothar.security.acl:strategy-spring-security-acl-elasticsearch:jar:1.3.0, com.github.lothar.security.acl:strategy-spring-security-acl-grant:jar:1.3.0, com.github.lothar.security.acl:strategy-spring-security-acl-jpa:jar:1.3.0: Failure to find com.github.lothar.security.acl:strategy-spring-security-acl-elasticsearch:jar:1.3.0 in https://raw.github.com/lordlothar99/strategy-spring-security-acl/mvn-repo/ was cached in the local repository, resolution will not be reattempted until the update interval of strategy-spring-security-acl-github-repo has elapsed or updates are forced -> [Help 1]
```

**Comment by lordlothar99** [comment]
My documentation was wrong, I'm sorry! The proper url for github repository is 
`https://raw.github.com/lordlothar99/mvn-repo/master/` since I moved to a centralized repo on Github. Please try with the config above
